from . import WikimediaTestCase


class WikimediaTest(WikimediaTestCase):
    def test_jpg(self):
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/400x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Christophe_Henner_-_June_2016.JPG'),
            '400px-Christophe_Henner_-_June_2016.jpg',
            '400px-Christophe_Henner_-_June_2016.png',
            400,
            267,
            0.92,
            1.02,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/400x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Christophe_Henner_-_June_2016.JPG'),
            '400px-Christophe_Henner_-_June_2016.jpg',
            '400px-Christophe_Henner_-_June_2016.png',
            400,
            267,
            0.94,
            0.80,
        )

    def test_request_by_height(self):
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/x267/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Christophe_Henner_-_June_2016.JPG'),
            '400px-Christophe_Henner_-_June_2016.jpg',
            '400px-Christophe_Henner_-_June_2016.png',
            400,
            267,
            0.92,
            1.02,
        )

    def test_request_specific_size(self):
        # Not currently used in WMF production
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/400x267/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Christophe_Henner_-_June_2016.JPG'),
            '400px-Christophe_Henner_-_June_2016.jpg',
            '400px-Christophe_Henner_-_June_2016.png',
            400,
            267,
            0.92,
            1.02,
        )

    def test_width_rounding(self):
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/800x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/Munich_subway_station_Westfriedhof.jpg'),
            '800px-Munich_subway_station_Westfriedhof.jpg',
            '800px-Munich_subway_station_Westfriedhof.png',
            800,
            353,
            0.91,
            1.03,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/800x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/Munich_subway_station_Westfriedhof.jpg'),
            '800px-Munich_subway_station_Westfriedhof.jpg',
            '800px-Munich_subway_station_Westfriedhof.png',
            800,
            353,
            0.91,
            0.77,
        )

    def test_exif_orientation(self):
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/40x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/EXIF_rotation_180.jpg',
            '40px-EXIF_rotation_180.jpg',
            '40px-EXIF_rotation_180.png',
            40,
            60,
            0.99,
            1.03,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/40x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/EXIF_rotation_180.jpg',
            '40px-EXIF_rotation_180.jpg',
            '40px-EXIF_rotation_180.png',
            40,
            60,
            0.99,
            0.28,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/337x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Green_and_golden_Butterfly_copy.jpg'),
            '337px-Green_and_golden_Butterfly_copy.jpg',
            '337px-Green_and_golden_Butterfly_copy.png',
            337,
            599,
            0.94,
            1.0,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/337x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Green_and_golden_Butterfly_copy.jpg'),
            '337px-Green_and_golden_Butterfly_copy.jpg',
            '337px-Green_and_golden_Butterfly_copy.png',
            337,
            599,
            0.96,
            0.97,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/394x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Rostockstein.jpg'),
            '394px-Rostockstein.jpg',
            '394px-Rostockstein.png',
            394,
            599,
            0.93,
            0.77,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/394x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Rostockstein.jpg'),
            '394px-Rostockstein.jpg',
            '394px-Rostockstein.png',
            394,
            599,
            0.97,
            0.81,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/450x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Carrie.jpg'),
            '450px-Carrie.jpg',
            '450px-Carrie.jpg',
            450,
            600,
            0.96,
            0.77,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/450x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Carrie.jpg'),
            '450px-Carrie.jpg',
            '450px-Carrie.png',
            450,
            600,
            0.97,
            0.65,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/447x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Cerkiew.jpg'),
            '447px-Cerkiew.jpg',
            '447px-Cerkiew.png',
            447,
            599,
            0.96,
            0.75,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/447x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Cerkiew.jpg'),
            '447px-Cerkiew.jpg',
            '447px-Cerkiew.png',
            447,
            599,
            0.96,
            0.57,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/337x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Tower.jpg'),
            '337px-Tower.jpg',
            '337px-Tower.png',
            337,
            600,
            0.96,
            0.81,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/337x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Tower.jpg'),
            '337px-Tower.jpg',
            '337px-Tower.png',
            337,
            600,
            0.98,
            0.83,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/400x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Magnus.jpg'),
            '400px-Magnus.jpg',
            '400px-Magnus.png',
            400,
            300,
            0.94,
            0.98,
        )
        self.run_and_check_ssim_and_size(
            ('/thumbor/unsafe/400x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85):format(webp)/'
                'Magnus.jpg'),
            '400px-Magnus.jpg',
            '400px-Magnus.png',
            400,
            300,
            0.96,
            0.92,
        )

    def test_bad_orientation(self):
        """Regression test for https://phabricator.wikimedia.org/T193326"""
        self.run_and_check_ssim_and_size(
            url=(
                '/thumbor/unsafe/450x/filters:conditional_sharpen(0.0,0.8,1.0,0.0,0.85)/'
                'Smedavska_hornatina_Sloupsky_potok_vodopad_01.jpg'
            ),
            mediawiki_reference_thumbnail=(
                '450px-Smedavska_hornatina_Sloupsky_potok_vodopad_01.jpg'
            ),
            perfect_reference_thumbnail=(
                '450px-Smedavska_hornatina_Sloupsky_potok_vodopad_01.jpg.png'
            ),
            expected_width=450,
            expected_height=600,
            expected_ssim=0.88,
            size_tolerance=0.83,
        )
