from . import WikimediaTestCase


class WikimediaTest(WikimediaTestCase):
    def test_tiff(self):
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/0729.tiff',
            'lossy-page1-400px-0729.tiff.jpg',
            'lossy-page1-400px-0729.tiff.png',
            400,
            254,
            0.97,
            0.68,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:format(webp)/0729.tiff',
            'lossy-page1-400px-0729.tiff.jpg',
            'lossy-page1-400px-0729.tiff.png',
            400,
            254,
            0.97,
            0.5,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/300x/Lejeune.TIF',
            'lossy-page1-300px-Lejeune.TIF.jpg',
            'lossy-page1-300px-Lejeune.TIF.png',
            300,
            202,
            0.98,
            0.23,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/300x/filters:format(webp)/Lejeune.TIF',
            'lossy-page1-300px-Lejeune.TIF.jpg',
            'lossy-page1-300px-Lejeune.TIF.png',
            300,
            202,
            0.97,
            0.64,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/300x/Hafnia_alvei.tif',
            'lossy-page1-300px-Hafnia_alvei.tif.jpg',
            'lossy-page1-300px-Hafnia_alvei.tif.png',
            300,
            300,
            0.95,
            0.48,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/300x/filters:format(webp)/Hafnia_alvei.tif',
            'lossy-page1-300px-Hafnia_alvei.tif.jpg',
            'lossy-page1-300px-Hafnia_alvei.tif.png',
            300,
            300,
            0.94,
            0.46,
        )

    def test_multipage_tiff(self):
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:page(3)/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page3-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page3-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.99,
            0.8,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:page(3):format(webp)/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page3-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page3-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.98,
            0.66,
        )

    def test_multipage_tiff_without_page_filter(self):
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.99,
            0.77,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:format(webp)/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.98,
            0.66,
        )

    def test_multipage_tiff_with_out_of_bounds_page(self):
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:page(500)/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.99,
            0.77,
        )
        self.run_and_check_ssim_and_size(
            '/thumbor/unsafe/400x/filters:page(500):format(webp)/International_Convention_for_Regulation_of_Whaling.tiff',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.jpg',
            'lossy-page1-400px-International_Convention_for_Regulation_of_Whaling.tiff.png',
            400,
            566,
            0.98,
            0.66,
        )
